using AviationFleet.Api.Models;

namespace AviationFleet.Api.Dtos;

public sealed record CreateMaintenanceTicketDto(Guid AircraftId, string IssueDescription, CertificationType RequiredCertification);

public sealed record MaintenanceTicketResponseDto(
    Guid Id,
    Guid AircraftId,
    Guid? MechanicId,
    string IssueDescription,
    CertificationType RequiredCertification,
    MaintenanceTicketStatus Status,
    DateTime DateCreated,
    bool IsAutoGenerated,
    AircraftPartType? RelatedPartType);

public sealed record MaintenanceTicketDetailDto(
    Guid Id,
    string TailNumber,
    string? MechanicName,
    string IssueDescription,
    CertificationType RequiredCertification,
    MaintenanceTicketStatus Status,
    string DateCreatedDisplay,
    bool IsAutoGenerated,
    string? RelatedPartLabel);

public sealed record AircraftWarningDto(Guid AircraftId, string TailNumber, double HoursRemainingUntilThreshold, string Message);
