using AviationFleet.Api.Data;
using AviationFleet.Api.Dtos;
using AviationFleet.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace AviationFleet.Api.Services;

public sealed class BusinessAnalyticsService(
    AviationFleetDbContext db,
    IFleetSettingsService fleetSettingsService) : IBusinessAnalyticsService
{
    private const decimal DirectOperatingCostPerBlockMinute = 100.76m;
    private const decimal MaintenanceCostPerBlockMinute = 18.30m;
    private const decimal PassengerTimeValuePerHour = 47m;
    private const decimal ConservativeAogDowntimeCostPerHour = 10000m;
    private const decimal IataHigherMaintenanceCost2025 = 3100000000m;
    private const int ProtectedHoursPerPredictiveTicket = 4;
    private const int ProtectedHoursPerAutoTicket = 2;
    private const decimal UnassignedTicketDelayHours = 1.5m;

    public async Task<BusinessDashboardDto> GetDashboardAsync(CancellationToken cancellationToken = default)
    {
        var settings = await fleetSettingsService.GetAsync(cancellationToken);
        var aircraft = await db.Aircraft
            .AsNoTracking()
            .Include(a => a.Parts)
            .ToListAsync(cancellationToken);
        var mechanics = await db.Mechanics
            .AsNoTracking()
            .ToListAsync(cancellationToken);
        var tickets = await db.MaintenanceTickets
            .AsNoTracking()
            .Include(t => t.Aircraft)
            .ToListAsync(cancellationToken);

        var activeTickets = tickets
            .Where(t => t.Status != MaintenanceTicketStatus.Completed)
            .ToList();
        var warnings = aircraft
            .Where(a => a.OperationalStatus != AircraftOperationalStatus.Unavailable)
            .Count(a => PredictiveMaintenanceRules.IsOnWarningRoster(
                a.TotalFlightHours,
                a.HoursAtLastMaintenance,
                a.MaintenanceThresholdHours));

        var readyAircraft = aircraft.Count(a => a.OperationalStatus == AircraftOperationalStatus.Ready);
        var assignedActiveJobs = activeTickets.Count(t => t.MechanicId.HasValue);
        var availableMechanics = mechanics.Where(m => m.IsAvailable).ToList();
        var totalCapacity = Math.Max(1, availableMechanics.Count * settings.MaxMechanicActiveJobs);
        var crewUtilization = Percent(assignedActiveJobs, totalCapacity);
        var autoGeneratedTickets = tickets.Count(t => t.IsAutoGenerated);
        var downtimeProtected = warnings * ProtectedHoursPerPredictiveTicket
            + autoGeneratedTickets * ProtectedHoursPerAutoTicket;
        var unassignedDelayHours = activeTickets.Count(t => !t.MechanicId.HasValue) * UnassignedTicketDelayHours;
        var directOperatingCostExposure = unassignedDelayHours * DirectOperatingCostPerBlockMinute * 60;
        var maintenanceCostAtRisk = activeTickets.Count * MaintenanceCostPerBlockMinute * 60;
        var aogExposureProtected = (decimal)downtimeProtected * ConservativeAogDowntimeCostPerHour;

        var allocation = BuildResourceAllocation(
            mechanics,
            activeTickets,
            settings.MaxMechanicActiveJobs);

        var kpis = new BusinessKpiDto(
            aircraft.Count,
            readyAircraft,
            Percent(readyAircraft, Math.Max(1, aircraft.Count)),
            activeTickets.Count,
            activeTickets.Count(t => !t.MechanicId.HasValue),
            crewUtilization,
            warnings,
            downtimeProtected,
            Math.Round(directOperatingCostExposure, 2),
            Math.Round(maintenanceCostAtRisk, 2),
            Math.Round(aogExposureProtected, 2),
            Math.Round(aogExposureProtected + maintenanceCostAtRisk + directOperatingCostExposure, 2));

        var insights = BuildInsights(kpis, allocation, aircraft, activeTickets);
        var trends = BuildTrends(aircraft, tickets, activeTickets, warnings);
        var actions = BuildActions(kpis, allocation, aircraft);
        var assumptions = BuildAssumptions();

        return new BusinessDashboardDto(
            DateTime.UtcNow,
            kpis,
            allocation,
            insights,
            trends,
            actions,
            assumptions);
    }

    private static IReadOnlyList<ResourceAllocationDto> BuildResourceAllocation(
        IReadOnlyList<Mechanic> mechanics,
        IReadOnlyList<MaintenanceTicket> activeTickets,
        int maxJobsPerMechanic)
    {
        return Enum.GetValues<CertificationType>()
            .Select(cert =>
            {
                var certifiedMechanics = mechanics
                    .Where(m => m.Certification == cert && m.IsAvailable)
                    .ToList();
                var capacity = certifiedMechanics.Count * maxJobsPerMechanic;
                var activeJobs = activeTickets.Count(t => t.RequiredCertification == cert && t.MechanicId.HasValue);
                var openBacklog = activeTickets.Count(t => t.RequiredCertification == cert);
                var unassigned = activeTickets.Count(t => t.RequiredCertification == cert && !t.MechanicId.HasValue);
                var remaining = Math.Max(0, capacity - activeJobs);
                var recommendation = unassigned > 0
                    ? $"Add or free {cert} capacity before dispatch delay compounds."
                    : remaining == 0 && openBacklog > 0
                        ? $"{cert} crew is saturated. Defer non-critical work or raise max jobs temporarily."
                        : remaining > 0 && openBacklog == 0
                            ? $"{cert} has spare capacity. Pull forward preventive work."
                            : $"{cert} allocation is balanced.";

                return new ResourceAllocationDto(
                    cert.ToString(),
                    certifiedMechanics.Count,
                    activeJobs,
                    openBacklog,
                    unassigned,
                    remaining,
                    Percent(activeJobs, Math.Max(1, capacity)),
                    recommendation);
            })
            .ToList();
    }

    private static IReadOnlyList<BusinessInsightDto> BuildInsights(
        BusinessKpiDto kpis,
        IReadOnlyList<ResourceAllocationDto> allocation,
        IReadOnlyList<Aircraft> aircraft,
        IReadOnlyList<MaintenanceTicket> activeTickets)
    {
        var insights = new List<BusinessInsightDto>();

        if (kpis.UnassignedTickets > 0)
        {
            insights.Add(new BusinessInsightDto(
                "Critical",
                "Dispatch demand exceeds certified crew capacity",
                $"{kpis.UnassignedTickets} active ticket(s) have no mechanic assigned.",
                "Work sits idle, aircraft downtime grows, and SLA confidence drops."));
        }

        if (kpis.PredictiveWarnings > 0)
        {
            insights.Add(new BusinessInsightDto(
                "High",
                "Preventive maintenance window is open",
                $"{kpis.PredictiveWarnings} aircraft are within 36 flight hours of maintenance due.",
                "Planning this work now protects schedule reliability and avoids expensive AOG events."));
        }

        var saturated = allocation.Where(a => a.UtilizationPercent >= 90).ToList();
        if (saturated.Count > 0)
        {
            insights.Add(new BusinessInsightDto(
                "High",
                "Crew utilization is near saturation",
                string.Join(", ", saturated.Select(a => $"{a.Certification} {a.UtilizationPercent:0}%")),
                "Small demand spikes can create queue delays unless work is rebalanced."));
        }

        var unavailable = aircraft.Count(a => a.OperationalStatus is AircraftOperationalStatus.InMaintenance
            or AircraftOperationalStatus.MaintenanceRequired
            or AircraftOperationalStatus.Unavailable);
        if (unavailable > 0)
        {
            insights.Add(new BusinessInsightDto(
                "Medium",
                "Fleet availability has revenue exposure",
                $"{unavailable} aircraft are not marked ready.",
                "Operations can prioritize aircraft that recover the most capacity fastest."));
        }

        if (activeTickets.Count == 0 && kpis.PredictiveWarnings == 0)
        {
            insights.Add(new BusinessInsightDto(
                "Low",
                "Maintenance demand is under control",
                "No active backlog or predictive warnings exist right now.",
                "Use spare capacity for inspections, training, and deferred preventive work."));
        }

        return insights;
    }

    private static IReadOnlyList<TrendSignalDto> BuildTrends(
        IReadOnlyList<Aircraft> aircraft,
        IReadOnlyList<MaintenanceTicket> tickets,
        IReadOnlyList<MaintenanceTicket> activeTickets,
        int warnings)
    {
        var autoRatio = tickets.Count == 0 ? 0 : Percent(tickets.Count(t => t.IsAutoGenerated), tickets.Count);
        var dueSoonPercent = Percent(warnings, Math.Max(1, aircraft.Count));
        var backlogByAircraft = aircraft.Count == 0 ? 0 : activeTickets.Count / (double)aircraft.Count;
        var notReadyPercent = Percent(
            aircraft.Count(a => a.OperationalStatus != AircraftOperationalStatus.Ready),
            Math.Max(1, aircraft.Count));

        return
        [
            new TrendSignalDto(
                "Predictive coverage",
                autoRatio >= 35 ? "Up" : "Flat",
                autoRatio,
                "%",
                "Share of tickets created automatically from flight-hour and component thresholds."),
            new TrendSignalDto(
                "Aircraft due soon",
                dueSoonPercent > 25 ? "Up" : "Stable",
                dueSoonPercent,
                "%",
                "Fleet share inside the 36-hour preventive maintenance window."),
            new TrendSignalDto(
                "Backlog density",
                backlogByAircraft > 1 ? "Up" : "Stable",
                backlogByAircraft,
                "tickets/aircraft",
                "Active maintenance load normalized by fleet size."),
            new TrendSignalDto(
                "Availability pressure",
                notReadyPercent > 20 ? "Up" : "Stable",
                notReadyPercent,
                "%",
                "Aircraft not currently ready for operations.")
        ];
    }

    private static IReadOnlyList<ActionRecommendationDto> BuildActions(
        BusinessKpiDto kpis,
        IReadOnlyList<ResourceAllocationDto> allocation,
        IReadOnlyList<Aircraft> aircraft)
    {
        var actions = new List<ActionRecommendationDto>();
        var constrained = allocation
            .Where(a => a.UnassignedBacklog > 0 || a.UtilizationPercent >= 90)
            .OrderByDescending(a => a.UnassignedBacklog)
            .ThenByDescending(a => a.UtilizationPercent)
            .FirstOrDefault();

        if (constrained is not null)
        {
            actions.Add(new ActionRecommendationDto(
                1,
                $"Rebalance {constrained.Certification} workload",
                "Maintenance operations",
                "Reduce unassigned backlog and protect aircraft return-to-service time."));
        }

        var nextDue = aircraft
            .Where(a => a.OperationalStatus != AircraftOperationalStatus.Unavailable)
            .Select(a => new
            {
                a.TailNumber,
                Remaining = PredictiveMaintenanceRules.HoursRemainingUntilMaintenanceDue(
                    a.TotalFlightHours,
                    a.HoursAtLastMaintenance,
                    a.MaintenanceThresholdHours)
            })
            .OrderBy(a => a.Remaining)
            .FirstOrDefault();

        if (nextDue is not null && nextDue.Remaining <= 36)
        {
            actions.Add(new ActionRecommendationDto(
                2,
                $"Schedule preventive slot for {nextDue.TailNumber}",
                "Planner",
                $"Avoid due-date breach in {nextDue.Remaining:0.#} flight hours."));
        }

        if (kpis.FleetAvailabilityPercent < 85)
        {
            actions.Add(new ActionRecommendationDto(
                3,
                "Prioritize fastest aircraft recovery",
                "Fleet manager",
                "Recover ready aircraft count before accepting low-margin rotations."));
        }

        actions.Add(new ActionRecommendationDto(
            actions.Count + 1,
            "Review monthly savings model with finance",
            "Operations leadership",
            $"Validate estimated protected downtime value of {kpis.EstimatedMonthlySavings:C0}."));

        return actions;
    }

    private static IReadOnlyList<BusinessAssumptionDto> BuildAssumptions() =>
    [
        new(
            "Direct aircraft operating cost",
            DirectOperatingCostPerBlockMinute,
            "USD per block minute",
            "Airlines for America 2024 DOT Form 41 summary",
            "https://www.airlines.org/dataset/u-s-passenger-carrier-delay-costs/"),
        new(
            "Maintenance operating cost",
            MaintenanceCostPerBlockMinute,
            "USD per block minute",
            "Airlines for America 2024 DOT Form 41 summary",
            "https://www.airlines.org/dataset/u-s-passenger-carrier-delay-costs/"),
        new(
            "Passenger time value",
            PassengerTimeValuePerHour,
            "USD per hour",
            "FAA-recommended value cited by Airlines for America",
            "https://www.airlines.org/dataset/u-s-passenger-carrier-delay-costs/"),
        new(
            "Conservative AOG downtime cost",
            ConservativeAogDowntimeCostPerHour,
            "USD per grounded hour",
            "Published AOG lower-bound industry estimate",
            "https://www.ironback.ai/glossary/aircraft-on-ground"),
        new(
            "2025 higher maintenance cost pressure",
            IataHigherMaintenanceCost2025,
            "USD",
            "IATA aviation supply chain impact estimate",
            "https://www.iata.org/en/programs/ops-infra/techops/aviation-supply-chain/")
    ];

    private static double Percent(double numerator, double denominator) =>
        denominator <= 0 ? 0 : Math.Round(numerator / denominator * 100, 1);
}
