using AviationFleet.Api.Models;
using AviationFleet.Api.Repositories;

namespace AviationFleet.Api.Services;

public sealed class FlightHoursAutomationService(
    IMaintenanceTicketRepository maintenanceTicketRepository,
    IDispatcherService dispatcherService) : IFlightHoursAutomationService
{
    public async Task<FlightHoursAutomationResult> RunAfterTotalHoursUpdatedAsync(
        Aircraft aircraft,
        double previousTotalFlightHours,
        CancellationToken cancellationToken = default)
    {
        var delta = aircraft.TotalFlightHours - previousTotalFlightHours;
        if (delta != 0)
        {
            foreach (var part in aircraft.Parts)
                part.HoursSinceLastMaintenance = Math.Max(0, part.HoursSinceLastMaintenance + delta);
        }

        if (aircraft.OperationalStatus == AircraftOperationalStatus.Unavailable)
            return new FlightHoursAutomationResult(false, false, null);

        var hoursSinceAirframe = aircraft.TotalFlightHours - aircraft.HoursAtLastMaintenance;
        var airframeExceeded = hoursSinceAirframe >= aircraft.MaintenanceThresholdHours;
        var partExceeded = aircraft.Parts.Any(p => p.HoursSinceLastMaintenance >= p.MaintenanceThresholdHours);
        var maintenanceNeeded = airframeExceeded || partExceeded;

        if (!maintenanceNeeded)
            return new FlightHoursAutomationResult(false, false, null);

        var locationLabel = aircraft.LocationState == AircraftLocationState.InAir ? "in flight" : "on the ground";
        var alert =
            $"ALERT: {aircraft.TailNumber} requires maintenance ({locationLabel}). "
            + (airframeExceeded ? "Airframe interval reached. " : string.Empty)
            + (partExceeded ? "One or more components exceeded their limits. " : string.Empty);

        if (aircraft.OperationalStatus == AircraftOperationalStatus.Ready)
            aircraft.OperationalStatus = AircraftOperationalStatus.MaintenanceRequired;

        var autoTicketCreated = false;
        if (aircraft.LocationState == AircraftLocationState.OnGround
            && !await maintenanceTicketRepository.HasActiveTicketForAircraftAsync(aircraft.Id, cancellationToken))
        {
            var primaryPart = aircraft.Parts
                .Where(p => p.HoursSinceLastMaintenance >= p.MaintenanceThresholdHours)
                .OrderByDescending(p => p.HoursSinceLastMaintenance - p.MaintenanceThresholdHours)
                .FirstOrDefault();

            var cert = primaryPart is not null
                ? PartCertificationMapper.ToCertification(primaryPart.PartType)
                : CertificationType.Engine;

            var desc = primaryPart is not null
                ? $"AUTO: Component {AircraftPartDisplay.Label(primaryPart.PartType)} exceeded maintenance threshold for {aircraft.TailNumber}."
                : $"AUTO: Airframe maintenance threshold exceeded for {aircraft.TailNumber}.";

            var ticket = new MaintenanceTicket
            {
                Id = Guid.NewGuid(),
                AircraftId = aircraft.Id,
                IssueDescription = desc,
                RequiredCertification = cert,
                Status = MaintenanceTicketStatus.Open,
                DateCreated = DateTime.UtcNow,
                IsAutoGenerated = true,
                RelatedPartType = primaryPart?.PartType,
            };

            maintenanceTicketRepository.Add(ticket);
            await dispatcherService.DispatchAsync(ticket, cancellationToken);
            if (ticket.MechanicId.HasValue)
                aircraft.OperationalStatus = AircraftOperationalStatus.InMaintenance;

            autoTicketCreated = true;
        }

        return new FlightHoursAutomationResult(true, autoTicketCreated, alert);
    }
}
