using System.Globalization;
using AviationFleet.Api.Dtos;
using AviationFleet.Api.Models;
using AviationFleet.Api.Repositories;

namespace AviationFleet.Api.Services;

public sealed class MaintenanceService(
    IAircraftRepository aircraftRepository,
    IMaintenanceTicketRepository maintenanceTicketRepository,
    IDispatcherService dispatcherService,
    IUnitOfWork unitOfWork) : IMaintenanceService
{
    public async Task<MaintenanceTicketResponseDto?> CreateTicketAsync(
        CreateMaintenanceTicketDto dto,
        CancellationToken cancellationToken = default)
    {
        var aircraft = await aircraftRepository.GetByIdAsync(dto.AircraftId, cancellationToken);
        if (aircraft is null)
            return null;

        var ticket = new MaintenanceTicket
        {
            Id = Guid.NewGuid(),
            AircraftId = dto.AircraftId,
            IssueDescription = dto.IssueDescription.Trim(),
            RequiredCertification = dto.RequiredCertification,
            Status = MaintenanceTicketStatus.Open,
            DateCreated = DateTime.UtcNow,
            IsAutoGenerated = false,
            RelatedPartType = null,
        };

        maintenanceTicketRepository.Add(ticket);
        await dispatcherService.DispatchAsync(ticket, cancellationToken);

        if (ticket.MechanicId.HasValue
            && aircraft.OperationalStatus != AircraftOperationalStatus.Unavailable)
            aircraft.OperationalStatus = AircraftOperationalStatus.InMaintenance;

        await unitOfWork.SaveChangesAsync(cancellationToken);
        return Map(ticket);
    }

    public async Task<IReadOnlyList<MaintenanceTicketDetailDto>> GetAllTicketsDetailedAsync(
        CancellationToken cancellationToken = default)
    {
        var rows = await maintenanceTicketRepository.GetAllWithDetailsAsync(cancellationToken);
        return rows.Select(MapDetail).ToList();
    }

    private static MaintenanceTicketResponseDto Map(MaintenanceTicket t) => new(
        t.Id,
        t.AircraftId,
        t.MechanicId,
        t.IssueDescription,
        t.RequiredCertification,
        t.Status,
        t.DateCreated,
        t.IsAutoGenerated,
        t.RelatedPartType);

    private static MaintenanceTicketDetailDto MapDetail(MaintenanceTicket t)
    {
        var tail = t.Aircraft?.TailNumber ?? t.AircraftId.ToString();
        var mech = t.Mechanic?.Name;
        var partLabel = t.RelatedPartType is { } part
            ? AircraftPartDisplay.Label(part)
            : null;
        return new MaintenanceTicketDetailDto(
            t.Id,
            tail,
            mech,
            t.IssueDescription,
            t.RequiredCertification,
            t.Status,
            FormatDisplayUtc(t.DateCreated),
            t.IsAutoGenerated,
            partLabel);
    }

    private static string FormatDisplayUtc(DateTime dateCreated) =>
        dateCreated.Kind == DateTimeKind.Unspecified
            ? DateTime.SpecifyKind(dateCreated, DateTimeKind.Utc)
                .ToUniversalTime()
                .ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture) + " UTC"
            : dateCreated.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture) + " UTC";
}
