using AviationFleet.Api.Models;
using AviationFleet.Api.Services;

namespace AviationFleet.Api.Data;

public static class DemoFleetSeeder
{
    public static Aircraft Aircraft(
        string tailNumber,
        double totalHours,
        double thresholdHours,
        double lastMaintenanceHours,
        AircraftLocationState location,
        AircraftOperationalStatus status)
    {
        var aircraft = new Aircraft
        {
            Id = Guid.NewGuid(),
            TailNumber = tailNumber,
            TotalFlightHours = totalHours,
            MaintenanceThresholdHours = thresholdHours,
            HoursAtLastMaintenance = lastMaintenanceHours,
            LocationState = location,
            OperationalStatus = status
        };

        AircraftPartDefaults.EnsureStandardParts(aircraft, Math.Max(0, totalHours - lastMaintenanceHours));
        return aircraft;
    }

    public static MaintenanceTicket Ticket(
        Aircraft aircraft,
        Mechanic? mechanic,
        string issue,
        CertificationType certification,
        MaintenanceTicketStatus status,
        bool isAutoGenerated,
        AircraftPartType? relatedPartType,
        int daysAgo) =>
        new()
        {
            Id = Guid.NewGuid(),
            AircraftId = aircraft.Id,
            MechanicId = mechanic?.Id,
            IssueDescription = issue,
            RequiredCertification = certification,
            Status = status,
            DateCreated = DateTime.UtcNow.AddDays(daysAgo),
            IsAutoGenerated = isAutoGenerated,
            RelatedPartType = relatedPartType
        };
}
