namespace AviationFleet.Api.Models;

public enum AircraftPartType
{
    Fuselage = 0,
    Engine = 1,
    LandingGear = 2,
    Avionics = 3,
    Hydraulics = 4,
    Apu = 5,
    WingStructure = 6,
    Empennage = 7,
    EngineCompressor = 8,
    EngineCombustor = 9,
    EngineTurbine = 10,
    EngineFuelControl = 11,
    NoseLandingGear = 12,
    BrakeAssembly = 13,
    WheelAndTire = 14,
    FlightComputer = 15,
    NavigationSystem = 16,
    CommunicationSystem = 17,
    Transponder = 18,
    HydraulicReservoir = 19,
    HydraulicActuator = 20,
    HydraulicLines = 21,
    ApuStarter = 22,
    ApuGenerator = 23,
    ApuFuelSystem = 24,
}
