using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AviationFleet.Api.Models;

public class MaintenanceTicket
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public Guid AircraftId { get; set; }

    [ForeignKey(nameof(AircraftId))]
    public Aircraft? Aircraft { get; set; }

    public Guid? MechanicId { get; set; }

    [ForeignKey(nameof(MechanicId))]
    public Mechanic? Mechanic { get; set; }

    [Required]
    [MaxLength(2000)]
    public string IssueDescription { get; set; } = string.Empty;

    public CertificationType RequiredCertification { get; set; }

    public MaintenanceTicketStatus Status { get; set; }

    public DateTime DateCreated { get; set; }

    public bool IsAutoGenerated { get; set; }

    public AircraftPartType? RelatedPartType { get; set; }
}
